### ISSUE TITLE
double #counties in evaluation

### ISSUE THREAD

**Issue by pnieters** [neuroinfo-os/BSTIM-Covid19#7]
the number of counties gets doubled in evaluate.py somewhere --

**Comment by lukeeffenberger** [comment]
could you specify?

**Comment by pnieters** [comment]
In the call to the metric functions f the shapes of the predicted datapoints and the real datapoints don't match in the county dimension -- which is strange.

**Comment by pnieters** [comment]
wrong files were loaded prev. not actually a code issue.
